name: Deploy to Hetzner

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Cache Docker layers
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/tdg-db .
          docker push ${{ secrets.DOCKER_USERNAME }}/tdg-db

      - name: SSH to Hetzner server and update
        uses: appleboy/ssh-action@v1.0.0 # Ensure you're using a suitable version
        with:
          host: ${{ secrets.HETZNER_HOST }}
          username: ${{ secrets.HETZNER_USER }}
          password: ${{ secrets.HETZNER_PASSWORD }} # Add password here for SSH login
          port: 22 # Optional: specify if SSH runs on a non-standard port
          script: |
            docker pull ${{ secrets.DOCKER_USERNAME }}/tdg-db
            docker stop tdg-db || true
            docker rm tdg-db || true
            docker run -d -p 5000:5000 --name tdg-db ${{ secrets.DOCKER_USERNAME }}/tdg-db
