name: Deploy to Hetzner

on:
  push:
    branches:
      - main # Or whatever branch you use

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Cache Docker layers
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        run: |
          docker build -t username/tdg-db .
          docker push username/tdg-db

      - name: SSH to Hetzner server and update
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.HETZNER_HOST }}
          username: ${{ secrets.HETZNER_USER }}
          key: ${{ secrets.HETZNER_PRIVATE_KEY }}
          script: |
            docker pull username/tdg-db
            docker stop tdg-db || true
            docker rm tdg-db || true
            docker run -d -p 5000:5000 --name tdg-db username/tdg-db
